### ISSUE TITLE
Error: Taxon was not found in sequence file

### ISSUE THREAD

**Issue by annmklein** [stephaneguindon/phyml#36] opened 2016-08-10 13:33 UTC
I want to build a tree using a topological constraint file. However, when PhyML reads my constraint tree file I get the following error: "== Taxon 'X' was not found in sequence file 'X.phyx'. I have double checked that the taxon names in the tree file and the alignment file do indeed match. I don't think it's an issue with length or content of the taxon names since the alignment file worked fine with jModelTest. I've attached the constraint tree and alignment files. Any help would be most appreciated!
-Ann

[order_constraint_file.txt](https://github.com/stephaneguindon/phyml/files/411164/order_constraint_file.txt)

[mcra_rep_set_refs_muscle_aligned_trim_edit.phyx.zip](https://github.com/stephaneguindon/phyml/files/411166/mcra_rep_set_refs_muscle_aligned_trim_edit.phyx.zip)

**Comment by stephaneguindon** [comment] 2016-08-12 14:01
Hi there,

I think I've found where the problem comes from. Unfortunately, I can't fix it right now on github (I'll probably do that some time next week). In the meantime, you can try fixing your sources by doing the following modifications:
in utilities.h: replace
#define  NODE_DEG_MAX        500
by
#define  NODE_DEG_MAX        2000
In utilities.c, replace
long_line[strlen(line)-1] = '\0';
by
long_line[strlen(line)-2] = '\0';

Let me know if it does not help.

Regards,

-Stephane-

**Comment by terrycojones** [comment] 2018-04-11 14:56
Did this get fixed?  A friend just ran into what looks like the same issue.

**Comment by stephaneguindon** [comment] 2018-04-12 13:35
I've juste tried a recent release with the example given above. It worked fine so I guess this problem is fixed in the recent versions of PhyML. Feel free to ask your friend to send me her/his data set and PhyML options.
Regards,
-Stephane-

**Comment by terrycojones** [comment] 2018-04-17 21:45
I just tried my friend's example file and the above issue (which I could reproduce, more or less) does occur with the latest phyml (according to `brew` that's 3.3.20180214). I run into another error, but will investigate that separately. Thanks @stephaneguindon :-)

I say "more or less" above, because in my case it was complaining that a taxon could not be found, but the taxon name it was printing had its final character missing. So it seems likely related to the above, judging from the suggested fix (though the fix looks like it would be removing an extra character, so I don't know...).

**Closed** 2019-04-28 08:32 UTC
