### ISSUE TITLE
make error on Ubuntu 16.04

### ISSUE THREAD

**Issue by lidaof** [stephaneguindon/phyml#146] opened 2021-07-06 02:53 UTC
Hi, trying to compile this tool on ubuntu 16.04, but get this error, am I missing any package? not sure from the error log 
thank in advance!
```bash

#./configure --enable-phyml

#make

.:  Building [phyml]. Version 3.3.20200621 :.


gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT utilities.o -MD -MP -MF .deps/utilities.Tpo -c -o utilities.o utilities.c
mv -f .deps/utilities.Tpo .deps/utilities.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT optimiz.o -MD -MP -MF .deps/optimiz.Tpo -c -o optimiz.o optimiz.c
mv -f .deps/optimiz.Tpo .deps/optimiz.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT lk.o -MD -MP -MF .deps/lk.Tpo -c -o lk.o lk.c
mv -f .deps/lk.Tpo .deps/lk.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT bionj.o -MD -MP -MF .deps/bionj.Tpo -c -o bionj.o bionj.c
mv -f .deps/bionj.Tpo .deps/bionj.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT models.o -MD -MP -MF .deps/models.Tpo -c -o models.o models.c
mv -f .deps/models.Tpo .deps/models.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT free.o -MD -MP -MF .deps/free.Tpo -c -o free.o free.c
mv -f .deps/free.Tpo .deps/free.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT help.o -MD -MP -MF .deps/help.Tpo -c -o help.o help.c
mv -f .deps/help.Tpo .deps/help.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT simu.o -MD -MP -MF .deps/simu.Tpo -c -o simu.o simu.c
mv -f .deps/simu.Tpo .deps/simu.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT eigen.o -MD -MP -MF .deps/eigen.Tpo -c -o eigen.o eigen.c
mv -f .deps/eigen.Tpo .deps/eigen.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT pars.o -MD -MP -MF .deps/pars.Tpo -c -o pars.o pars.c
mv -f .deps/pars.Tpo .deps/pars.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT alrt.o -MD -MP -MF .deps/alrt.Tpo -c -o alrt.o alrt.c
mv -f .deps/alrt.Tpo .deps/alrt.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT interface.o -MD -MP -MF .deps/interface.Tpo -c -o interface.o interface.c
mv -f .deps/interface.Tpo .deps/interface.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT cl.o -MD -MP -MF .deps/cl.Tpo -c -o cl.o cl.c
mv -f .deps/cl.Tpo .deps/cl.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT spr.o -MD -MP -MF .deps/spr.Tpo -c -o spr.o spr.c
mv -f .deps/spr.Tpo .deps/spr.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT draw.o -MD -MP -MF .deps/draw.Tpo -c -o draw.o draw.c
mv -f .deps/draw.Tpo .deps/draw.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT stats.o -MD -MP -MF .deps/stats.Tpo -c -o stats.o stats.c
mv -f .deps/stats.Tpo .deps/stats.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT rates.o -MD -MP -MF .deps/rates.Tpo -c -o rates.o rates.c
mv -f .deps/rates.Tpo .deps/rates.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT mcmc.o -MD -MP -MF .deps/mcmc.Tpo -c -o mcmc.o mcmc.c
mv -f .deps/mcmc.Tpo .deps/mcmc.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT times.o -MD -MP -MF .deps/times.Tpo -c -o times.o times.c
mv -f .deps/times.Tpo .deps/times.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT tiporder.o -MD -MP -MF .deps/tiporder.Tpo -c -o tiporder.o tiporder.c
mv -f .deps/tiporder.Tpo .deps/tiporder.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT io.o -MD -MP -MF .deps/io.Tpo -c -o io.o io.c
mv -f .deps/io.Tpo .deps/io.Po
gcc  -I. -I..     -std=c99 -O3 -fomit-frame-pointer -funroll-loops -Wall -Winline -finline -march=native -MT make.o -MD -MP -MF .deps/make.Tpo -c -o make.o make.c
make.c: In function ‘Make_Tree_For_Lk’:
make.c:45:92: error: ‘__m256d’ undeclared (first use in this function)
   if(posix_memalign((void **)&tree->_tPij1,BYTE_ALIGN,(size_t)(ncatg * nsns / sz) * sizeof(__m256d))) Generic_Exit(__FILE__,__LINE__,__FUNCTION__);
                                                                                            ^
make.c:45:92: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1766: recipe for target 'make.o' failed
make[2]: *** [make.o] Error 1
make[2]: Leaving directory '/opt/apps/phyml/src'
Makefile:364: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/apps/phyml'
Makefile:305: recipe for target 'all' failed
make: *** [all] Error 2

```

```bash

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 

```

**Comment by stephaneguindon** [comment] 2021-07-08 09:31
Not sure what the problem is here.
Would you mind sending me the output of the following command:
gcc -march=native  -dM -E - < /dev/null | egrep "SSE|AVX" | sort
This is to find out about AVX, SSE intrinsics installed on your system

**Comment by lidaof** [comment] 2021-07-08 14:59
Thank you for your reply @stephaneguindon 

here is the output:

```bash
$ gcc -march=native -dM -E - < /dev/null | egrep "SSE|AVX" | sort
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE_MATH__ 1
#define __SSSE3__ 1
```

**Comment by stephaneguindon** [comment] 2021-07-12 09:00
This issue should be fixed now. See 8464f64b6c1b8c3e7e77e79171111c20c821b454

**Comment by lidaof** [comment] 2021-07-12 14:14
it works now! thank you so much! @stephaneguindon

**Closed** 2021-07-12 14:34 UTC
